# Create secret for admin credentials
apiVersion: v1
kind: Secret
metadata:
  name: example-grafana-admin-credentials
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: grafana-operator
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: YWRtaW4=  # Base64 encoded "admin"
  GF_SECURITY_ADMIN_PASSWORD: aVhJWEFHR0dmcnQ0V3c9PQ==  # Base64 encoded password (example: "admin123")
